site_name: OralSMP Wiki
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - content.tooltips
  palette: 
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - abbr
  - pymdownx.snippets
  - md_in_html
nav:
  - Home: index.md
  - Installation: setup/installation.md
  - Mechanics: mechanics/enchanting.md
